---
title: "DEG_tumor_type"
author: "Christoph Luh"
date: "2025-11-08"
output: html_document
---
---
title: "DESeq2_expression"
author: "Christoph Luh"
date: "2025-11-07"
output: html_document
---

#Load and filter 
```{bash}
git checkout chris
```

```{r}
#Read meta_data
meta_data <- read.csv("meta_data_unfiltered", row.names = 1)
meta_data <- data.frame(Run = meta_data$Run, history = meta_data$history)

#Remove unwanted histroy
exclude_terms <- c(
  "recurrent astrocytomas",
  "secondary Glioblastomas",
  "recurrent anaplastic oligodendrogliomas",
  "recurrent anaplastic astrocytomas",
  "recurrent anaplastic oligodendroastrocytomas",
  "recurrent Glioblastomas",
  "recurrent oligodendroastrocytomas"
)

meta_data <- meta_data[!(meta_data$history %in% exclude_terms), ]

meta_data$severity <- ifelse(
  grepl("anaplastic|primary", meta_data$history, ignore.case = TRUE),
  "high",
  "low"
)

#Create filtering columns
tumor_types <- c("astrocytomas", "oligodendroastrocytomas", "oligodendrogliomas")

for (tumor in tumor_types) {
  col_name <- tumor
  
  meta_data[[col_name]] <- ifelse(
    meta_data$history %in% c(tumor, paste("anaplastic", tumor)),
    1,
    0
  )
}

meta_data$glioblastomas <- ifelse(
  meta_data$history %in% c("primary Glioblastomas"),
  1,
  0
)

print(meta_data)

```

#Load and filter expression data
```{bash}
git checkout main
```

```{r}
expr <- read.csv("expression_matrix.csv", row.names = 1)
expr <- expr[colnames(expr) %in% meta_data$Run]
expr
```

```{r}
library(biomaRt)
library(dplyr)


ensembl <- useEnsembl(biomart = "ensembl",
                      dataset = "hsapiens_gene_ensembl")
meta_genes <- getBM(attributes = c("ensembl_gene_id",
                                   "ensembl_gene_id_version",
                                   "hgnc_symbol",
                                   "description",
                                   "chromosome_name",
                                   "start_position",
                                   "end_position",
                                   "strand"),
                    filters = "ensembl_gene_id_version",
                    values = rownames(expr),
                    mart = ensembl) %>%
  right_join(data.frame(ensembl_gene_id_version = rownames(expr)),
             by = "ensembl_gene_id_version") %>%
  distinct(ensembl_gene_id_version, .keep_all = TRUE)


expr <- expr[meta_genes$ensembl_gene_id_version,]

```
```{r}
library(ggplot2)
num_det <- rowSums(expr > 0)
hist(num_det)
expressed <- rowMeans(expr > 0) >= 0.5 | rowMeans(expr) >= 1
meta_genes$expressed <- expressed
```

#Load DDS File
```{r}
library(DESeq2)
dds <- readRDS("dds.rds")
```

#Add the sample names to the dds object
```{r}
colnames(dds) <- colnames(read.csv("expression_matrix.csv", row.names = 1))
rownames(colData(dds)) <- colData(dds)$Run
```

#Clean the colData(dds) from all the secondary/recursive tumors by using meta_data
```{r}
# 1️⃣ Filter samples im dds, die nicht in meta_data enthalten sind
dds <- dds[, colnames(dds) %in% meta_data$Run]

# 2️⃣ Bringe colData(dds) in die Reihenfolge von meta_data
dds <- dds[, match(meta_data$Run, colnames(dds))]

# 3️⃣ Prüfen, ob alles korrekt übereinstimmt
all(colnames(dds) == meta_data$Run)  # sollte TRUE ergeben

```
#Factorize History
```{r}
colData(dds)$history <- as.factor(colData(dds)$history)
```

#Remove unused histories (No factor should have 0 usages in the table)
```{r}
colData(dds)$history <- droplevels(colData(dds)$history)
levels(colData(dds)$history)   # kontrollieren
table(colData(dds)$history)    # kontrollieren

```


```{r}
colData(dds)$history <- relevel(colData(dds)$history, ref = "astrocytomas")
levels(colData(dds)$history)
design(dds) <- ~ history
dds_history <- DESeq(dds)
```

#Astro vs GBM
```{r}
res_astro <- results(dds_history, contrast = c("history", "anaplastic astrocytomas", "primary Glioblastomas"))

# Volcano plot
library(ggplot2)

res_df <- as.data.frame(res_astro)
res_df$significant <- ifelse(
  res_df$padj < 0.1 & abs(res_df$log2FoldChange) > 1,
  "Significant", "Not significant"
)

ggplot(res_df, aes(x = log2FoldChange, y = -log10(pvalue), color = significant)) +
  geom_point(alpha = 0.8, size = 2) +
  scale_color_manual(values = c("gray70", "red")) +
  theme_minimal() +
  labs(title = "Volcano Plot: Anaplastic Astrocytomas vs parimary Glioblastomas",
       x = "log2 Fold Change (High vs Low)",
       y = "-log10(p-value)")

```


```{r}
#Low Grade Astrocytoma vs. Anaplastic Astrocytoma
res_LGA_APA <- as.data.frame(results(dds_history, contrast = c("history", "astrocytomas", "anaplastic astrocytomas")))
sig_LGA_APA <- res_LGA_APA[!is.na(res_LGA_APA$padj) & res_LGA_APA$padj < 0.05, ]

#Low Grade Astrocytoma vs. Primary Glioblastoma
res_LGA_GBM <- as.data.frame(results(dds_history, contrast = c("history", "astrocytomas", "primary Glioblastomas")))
sig_LGA_GBM <- res_LGA_GBM[!is.na(res_LGA_GBM$padj) & res_LGA_GBM$padj < 0.05, ]

#Low Anaplastic Astrocytoma vs. Primary Glioblastoma
res_APA_GBM <- as.data.frame(results(dds_history, contrast = c("history", "anaplastic astrocytomas", "primary Glioblastomas")))
sig_APA_GBM <- res_APA_GBM[!is.na(res_APA_GBM$padj) & res_APA_GBM$padj < 0.05, ]
```

```{r}
sig_LGA_APA
sig_LGA_GBM
sig_APA_GBM

```

```{r}
DEG_all_astrocytomas <- unique(c(rownames(sig_LGA_APA), rownames(sig_LGA_GBM), rownames(sig_APA_GBM)))
DEG_all_astrocytomas
```

```{r}
unique(meta_data$history)
```


```{r}
expr[DEG_all_astrocytomas, meta_data$history %in% c("astrocytomas", "primary Glioblastomas", "anaplastic astrocytomas")]
```

```{r}
DEG_expr <- data.frame(matrix(0, 
                        nrow = length(DEG_all_astrocytomas), 
                        ncol = length(c("astrocytomas", "anaplastic astrocytomas", "primary Glioblastomas")),
                        dimnames = list(DEG_all_astrocytomas, c("astrocytomas", "anaplastic astrocytomas", "primary Glioblastomas"))),
  check.names = FALSE)

for (tumor in c("astrocytomas", "anaplastic astrocytomas", "primary Glioblastomas")){
  DEG_expr[, tumor] <- rowMeans(expr[DEG_all_astrocytomas, meta_data[meta_data$history %in% tumor, ]$Run])
}
DEG_expr 
```
```{r}
write.csv2(DEG_expr, "DEG_expr.csv", row.names = TRUE)
```

```{r}
library(ggplot2)
TOI <- c("astrocytomas", "anaplastic astrocytomas", "primary Glioblastomas")
expr_1 <- as.data.frame(meta_data[meta_data$history %in% TOI, c("Run", "history")])

for (gene in DEG_all_astrocytomas){
  expr_1[, gene] <- t(expr[gene, expr_1$Run])
}

expr_1$ENSG00000052850.8
```

```{r}
library(ggplot2)

for (gene in DEG_all_astrocytomas) {
  b <- ggplot(expr_1, aes(x = history, y = .data[[gene]], fill = history)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.4) +
  theme_bw() +
  labs(title = gene, x = "Tumor Type", y = "Expression Level")

  print(b)
}

```



```{r}
library(ggplot2)

for (gene in DEG_all_astrocytomas) {
  v <- ggplot(expr_1, aes(x = history, y = .data[[gene]], fill = history)) +
  geom_violin(trim = FALSE, alpha = 0.6) +
  geom_boxplot(width = 0.1, fill = "white") +
  theme_bw()


  print(v)
}

```
```{r}
library(pheatmap)
# Relevante Tumortypen
TOI <- c("astrocytomas", "anaplastic astrocytomas", "primary Glioblastomas")

# Nur die Samples behalten, die in TOI vorkommen
meta_sub <- meta_data[meta_data$history %in% TOI, ]

# Gleiche Reihenfolge wie in expr sicherstellen
meta_sub <- meta_sub[meta_sub$Run %in% colnames(expr), ]

# Und ggf. expr auf diese Samples beschränken
expr_sub <- expr[, meta_sub$Run]

library(pheatmap)

annotation_col <- data.frame(history = meta_sub$history)
rownames(annotation_col) <- meta_sub$Run

pheatmap(expr_sub[DEG_all_astrocytomas, ],
         annotation_col = annotation_col,
         scale = "row",
         show_rownames = FALSE)


```

```{r}
rld <- rlog(dds_history, blind = FALSE)
plotPCA(rld, intgroup = "history")

```




```{r}
library(org.Hs.eg.db)
library(clusterProfiler)

# Beispiel: Ensembl IDs ohne Versionsnummer
gene_ids <- gsub("\\..*", "", DEG_all_astrocytomas)

# Umwandeln zu Symbolen
gene_symbols <- mapIds(org.Hs.eg.db,
                       keys = gene_ids,
                       column = "SYMBOL",
                       keytype = "ENSEMBL",
                       multiVals = "first")

```