{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2d79b8fd-3a95-494f-95f0-4de01e3f0356",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "also installing the dependencies ‘bitops’, ‘gtools’, ‘caTools’, ‘assertthat’, ‘babelgene’\n",
      "\n",
      "\n",
      "Updating HTML index of packages in '.Library'\n",
      "\n",
      "Making 'packages.html' ...\n",
      " done\n",
      "\n",
      "'getOption(\"repos\")' replaces Bioconductor standard repositories, see\n",
      "'help(\"repositories\", package = \"BiocManager\")' for details.\n",
      "Replacement repositories:\n",
      "    CRAN: https://cran.r-project.org\n",
      "\n",
      "Bioconductor version 3.18 (BiocManager 1.30.26), R 4.3.1 (2023-06-16)\n",
      "\n",
      "Installing package(s) 'BiocVersion', 'biomaRt', 'sva', 'DESeq2', 'edgeR'\n",
      "\n",
      "also installing the dependencies ‘DBI’, ‘plogr’, ‘png’, ‘Biostrings’, ‘lambda.r’, ‘futile.options’, ‘RCurl’, ‘GenomeInfoDbData’, ‘zlibbioc’, ‘abind’, ‘SparseArray’, ‘RSQLite’, ‘KEGGREST’, ‘filelock’, ‘annotate’, ‘futile.logger’, ‘snow’, ‘BH’, ‘statmod’, ‘GenomeInfoDb’, ‘XVector’, ‘S4Arrays’, ‘DelayedArray’, ‘Rcpp’, ‘XML’, ‘AnnotationDbi’, ‘BiocFileCache’, ‘genefilter’, ‘BiocParallel’, ‘matrixStats’, ‘limma’, ‘S4Vectors’, ‘IRanges’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘BiocGenerics’, ‘Biobase’, ‘locfit’, ‘MatrixGenerics’, ‘RcppArmadillo’\n",
      "\n",
      "\n",
      "Updating HTML index of packages in '.Library'\n",
      "\n",
      "Making 'packages.html' ...\n",
      " done\n",
      "\n",
      "Old packages: 'askpass', 'backports', 'bit', 'bit64', 'boot', 'broom', 'bslib',\n",
      "  'cachem', 'callr', 'caret', 'class', 'cli', 'clock', 'cluster', 'codetools',\n",
      "  'colorspace', 'commonmark', 'cpp11', 'crayon', 'curl', 'data.table',\n",
      "  'dbplyr', 'digest', 'dplyr', 'dtplyr', 'e1071', 'evaluate', 'fansi',\n",
      "  'farver', 'fastmap', 'fontawesome', 'forcats', 'foreign', 'fs', 'future',\n",
      "  'future.apply', 'gargle', 'generics', 'ggplot2', 'glmnet', 'globals', 'glue',\n",
      "  'googledrive', 'googlesheets4', 'gower', 'gtable', 'hardhat', 'haven',\n",
      "  'highr', 'hms', 'htmltools', 'httpuv', 'ipred', 'jsonlite', 'KernSmooth',\n",
      "  'knitr', 'later', 'lattice', 'lava', 'lifecycle', 'listenv', 'lubridate',\n",
      "  'magrittr', 'mgcv', 'mime', 'munsell', 'nlme', 'nnet', 'openssl',\n",
      "  'parallelly', 'pbdZMQ', 'pillar', 'pROC', 'processx', 'prodlim', 'progress',\n",
      "  'progressr', 'promises', 'ps', 'purrr', 'quantmod', 'R6', 'ragg',\n",
      "  'randomForest', 'RcppEigen', 'readr', 'readxl', 'recipes', 'repr', 'reprex',\n",
      "  'rlang', 'rmarkdown', 'rpart', 'rstudioapi', 'rvest', 'sass', 'scales',\n",
      "  'shape', 'shiny', 'spatial', 'stringi', 'stringr', 'survival', 'sys',\n",
      "  'systemfonts', 'textshaping', 'tibble', 'tidyr', 'tidyselect', 'timechange',\n",
      "  'timeDate', 'tinytex', 'TTR', 'tzdb', 'utf8', 'uuid', 'vctrs', 'vroom',\n",
      "  'withr', 'xfun', 'xml2', 'xts', 'yaml', 'zoo'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "install.packages(c(\"tidyverse\",\"ggrepel\",\"BiocManager\",\"pbapply\",\"gplots\",\"msigdbr\"))\n",
    "BiocManager::install(c(\"biomaRt\",\"sva\",\"DESeq2\",\"edgeR\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ec467fc3-4cdd-4577-8d0c-9e3a9714be53",
   "metadata": {},
   "outputs": [],
   "source": [
    "setwd(\"/cluster/scratch/aingemansson\")\n",
    "\n",
    "samples <- list.files(\"rsem\")\n",
    "expr <- sapply(samples, function(sample){\n",
    "  file <- paste0(\"rsem/\",sample,\"/\",sample,\".genes.results\")\n",
    "  quant <- read.csv(file, sep=\"\\t\", header=T)\n",
    "  tpm <- setNames(quant$TPM, quant$gene_id)\n",
    "  return(tpm)\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f760b83e-7e15-4012-92ab-15f4514fd5fc",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table class=\"dataframe\">\n",
       "<caption>A data.frame: 30 × 2</caption>\n",
       "<thead>\n",
       "\t<tr><th scope=col>Run</th><th scope=col>history</th></tr>\n",
       "\t<tr><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;chr&gt;</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "\t<tr><td>SRR934717</td><td>oligodendroastrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934718</td><td>oligodendroastrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934719</td><td>oligodendrogliomas                </td></tr>\n",
       "\t<tr><td>SRR934724</td><td>astrocytomas                      </td></tr>\n",
       "\t<tr><td>SRR934732</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934733</td><td>oligodendrogliomas                </td></tr>\n",
       "\t<tr><td>SRR934734</td><td>anaplastic oligodendrogliomas     </td></tr>\n",
       "\t<tr><td>SRR934736</td><td>astrocytomas                      </td></tr>\n",
       "\t<tr><td>SRR934741</td><td>anaplastic oligodendroastrocytomas</td></tr>\n",
       "\t<tr><td>SRR934743</td><td>anaplastic oligodendroastrocytomas</td></tr>\n",
       "\t<tr><td>SRR934746</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934747</td><td>anaplastic astrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934756</td><td>anaplastic oligodendrogliomas     </td></tr>\n",
       "\t<tr><td>SRR934768</td><td>oligodendrogliomas                </td></tr>\n",
       "\t<tr><td>SRR934770</td><td>oligodendrogliomas                </td></tr>\n",
       "\t<tr><td>SRR934772</td><td>anaplastic astrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934796</td><td>oligodendroastrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934803</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934808</td><td>astrocytomas                      </td></tr>\n",
       "\t<tr><td>SRR934815</td><td>anaplastic astrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934817</td><td>anaplastic astrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934829</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934833</td><td>oligodendroastrocytomas           </td></tr>\n",
       "\t<tr><td>SRR934861</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934893</td><td>anaplastic oligodendrogliomas     </td></tr>\n",
       "\t<tr><td>SRR934899</td><td>anaplastic oligodendroastrocytomas</td></tr>\n",
       "\t<tr><td>SRR934904</td><td>anaplastic oligodendroastrocytomas</td></tr>\n",
       "\t<tr><td>SRR934914</td><td>anaplastic oligodendrogliomas     </td></tr>\n",
       "\t<tr><td>SRR934927</td><td>primary Glioblastomas             </td></tr>\n",
       "\t<tr><td>SRR934947</td><td>astrocytomas                      </td></tr>\n",
       "</tbody>\n",
       "</table>\n"
      ],
      "text/latex": [
       "A data.frame: 30 × 2\n",
       "\\begin{tabular}{ll}\n",
       " Run & history\\\\\n",
       " <chr> & <chr>\\\\\n",
       "\\hline\n",
       "\t SRR934717 & oligodendroastrocytomas           \\\\\n",
       "\t SRR934718 & oligodendroastrocytomas           \\\\\n",
       "\t SRR934719 & oligodendrogliomas                \\\\\n",
       "\t SRR934724 & astrocytomas                      \\\\\n",
       "\t SRR934732 & primary Glioblastomas             \\\\\n",
       "\t SRR934733 & oligodendrogliomas                \\\\\n",
       "\t SRR934734 & anaplastic oligodendrogliomas     \\\\\n",
       "\t SRR934736 & astrocytomas                      \\\\\n",
       "\t SRR934741 & anaplastic oligodendroastrocytomas\\\\\n",
       "\t SRR934743 & anaplastic oligodendroastrocytomas\\\\\n",
       "\t SRR934746 & primary Glioblastomas             \\\\\n",
       "\t SRR934747 & anaplastic astrocytomas           \\\\\n",
       "\t SRR934756 & anaplastic oligodendrogliomas     \\\\\n",
       "\t SRR934768 & oligodendrogliomas                \\\\\n",
       "\t SRR934770 & oligodendrogliomas                \\\\\n",
       "\t SRR934772 & anaplastic astrocytomas           \\\\\n",
       "\t SRR934796 & oligodendroastrocytomas           \\\\\n",
       "\t SRR934803 & primary Glioblastomas             \\\\\n",
       "\t SRR934808 & astrocytomas                      \\\\\n",
       "\t SRR934815 & anaplastic astrocytomas           \\\\\n",
       "\t SRR934817 & anaplastic astrocytomas           \\\\\n",
       "\t SRR934829 & primary Glioblastomas             \\\\\n",
       "\t SRR934833 & oligodendroastrocytomas           \\\\\n",
       "\t SRR934861 & primary Glioblastomas             \\\\\n",
       "\t SRR934893 & anaplastic oligodendrogliomas     \\\\\n",
       "\t SRR934899 & anaplastic oligodendroastrocytomas\\\\\n",
       "\t SRR934904 & anaplastic oligodendroastrocytomas\\\\\n",
       "\t SRR934914 & anaplastic oligodendrogliomas     \\\\\n",
       "\t SRR934927 & primary Glioblastomas             \\\\\n",
       "\t SRR934947 & astrocytomas                      \\\\\n",
       "\\end{tabular}\n"
      ],
      "text/markdown": [
       "\n",
       "A data.frame: 30 × 2\n",
       "\n",
       "| Run &lt;chr&gt; | history &lt;chr&gt; |\n",
       "|---|---|\n",
       "| SRR934717 | oligodendroastrocytomas            |\n",
       "| SRR934718 | oligodendroastrocytomas            |\n",
       "| SRR934719 | oligodendrogliomas                 |\n",
       "| SRR934724 | astrocytomas                       |\n",
       "| SRR934732 | primary Glioblastomas              |\n",
       "| SRR934733 | oligodendrogliomas                 |\n",
       "| SRR934734 | anaplastic oligodendrogliomas      |\n",
       "| SRR934736 | astrocytomas                       |\n",
       "| SRR934741 | anaplastic oligodendroastrocytomas |\n",
       "| SRR934743 | anaplastic oligodendroastrocytomas |\n",
       "| SRR934746 | primary Glioblastomas              |\n",
       "| SRR934747 | anaplastic astrocytomas            |\n",
       "| SRR934756 | anaplastic oligodendrogliomas      |\n",
       "| SRR934768 | oligodendrogliomas                 |\n",
       "| SRR934770 | oligodendrogliomas                 |\n",
       "| SRR934772 | anaplastic astrocytomas            |\n",
       "| SRR934796 | oligodendroastrocytomas            |\n",
       "| SRR934803 | primary Glioblastomas              |\n",
       "| SRR934808 | astrocytomas                       |\n",
       "| SRR934815 | anaplastic astrocytomas            |\n",
       "| SRR934817 | anaplastic astrocytomas            |\n",
       "| SRR934829 | primary Glioblastomas              |\n",
       "| SRR934833 | oligodendroastrocytomas            |\n",
       "| SRR934861 | primary Glioblastomas              |\n",
       "| SRR934893 | anaplastic oligodendrogliomas      |\n",
       "| SRR934899 | anaplastic oligodendroastrocytomas |\n",
       "| SRR934904 | anaplastic oligodendroastrocytomas |\n",
       "| SRR934914 | anaplastic oligodendrogliomas      |\n",
       "| SRR934927 | primary Glioblastomas              |\n",
       "| SRR934947 | astrocytomas                       |\n",
       "\n"
      ],
      "text/plain": [
       "   Run       history                           \n",
       "1  SRR934717 oligodendroastrocytomas           \n",
       "2  SRR934718 oligodendroastrocytomas           \n",
       "3  SRR934719 oligodendrogliomas                \n",
       "4  SRR934724 astrocytomas                      \n",
       "5  SRR934732 primary Glioblastomas             \n",
       "6  SRR934733 oligodendrogliomas                \n",
       "7  SRR934734 anaplastic oligodendrogliomas     \n",
       "8  SRR934736 astrocytomas                      \n",
       "9  SRR934741 anaplastic oligodendroastrocytomas\n",
       "10 SRR934743 anaplastic oligodendroastrocytomas\n",
       "11 SRR934746 primary Glioblastomas             \n",
       "12 SRR934747 anaplastic astrocytomas           \n",
       "13 SRR934756 anaplastic oligodendrogliomas     \n",
       "14 SRR934768 oligodendrogliomas                \n",
       "15 SRR934770 oligodendrogliomas                \n",
       "16 SRR934772 anaplastic astrocytomas           \n",
       "17 SRR934796 oligodendroastrocytomas           \n",
       "18 SRR934803 primary Glioblastomas             \n",
       "19 SRR934808 astrocytomas                      \n",
       "20 SRR934815 anaplastic astrocytomas           \n",
       "21 SRR934817 anaplastic astrocytomas           \n",
       "22 SRR934829 primary Glioblastomas             \n",
       "23 SRR934833 oligodendroastrocytomas           \n",
       "24 SRR934861 primary Glioblastomas             \n",
       "25 SRR934893 anaplastic oligodendrogliomas     \n",
       "26 SRR934899 anaplastic oligodendroastrocytomas\n",
       "27 SRR934904 anaplastic oligodendroastrocytomas\n",
       "28 SRR934914 anaplastic oligodendrogliomas     \n",
       "29 SRR934927 primary Glioblastomas             \n",
       "30 SRR934947 astrocytomas                      "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "library(dplyr)\n",
    "\n",
    "# Läs in listan av SRR-accessioner\n",
    "srr_list <- readLines(\"SRR_Acc_List.txt\")\n",
    "\n",
    "# Läs in SraRunTable och filtrera\n",
    "sra_filtered <- read.csv(\"SraRunTable.csv\", header = TRUE) %>%\n",
    "  filter(Run %in% srr_list)\n",
    "\n",
    "# Visa resultatet\n",
    "sra_filtered_subset <- sra_filtered %>%\n",
    "  select(Run, history)\n",
    "\n",
    "sra_filtered_subset"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.3.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
